### ISSUE TITLE
スケッチが書き込めなくなる

### ISSUE THREAD

**Issue by matsujirushi** [SeeedJP/WioLTEforArduino#12]
Arduino IDEからスケッチ（プログラム）を書き込もうとすると、下記エラーが発生する。

```
Archiving built core (caching) in: C:\Users\takashi\AppData\Local\Temp\arduino_cache_726229\core\core_Seeeduino_Seeed_STM32F4_wioGpsM4_26ea3cd2d55d0e85c00ac4fc67ac5b73.a
最大1048576バイトのフラッシュメモリのうち、スケッチが18348バイト（1%）を使っています。
グローバル変数は13808バイトのRAMを使用しています。
シリアルポート「COM20」を1200bpsで開いて閉じる事によって、リセットを行っています。
processing.app.debug.RunnerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:160)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.SketchController.upload(SketchController.java:713)
	at processing.app.SketchController.exportApplet(SketchController.java:686)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2149)
	at java.lang.Thread.run(Thread.java:745)
Caused by: processing.app.SerialException: シリアルポート「COM20」をタッチできませんでした。
	at processing.app.Serial.touchForCDCReset(Serial.java:99)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:144)
	... 5 more
Caused by: jssc.SerialPortException: Port name - COM20; Method name - openPort(); Exception type - Port not found.
	at jssc.SerialPort.openPort(SerialPort.java:167)
	at processing.app.Serial.touchForCDCReset(Serial.java:93)
	... 6 more
```

**Comment by matsujirushi** [comment]
Wio LTEを通常モードで起動しておき、
1. Arduino IDEを起動
2. シリアルモニタを立ち上げる
3. （シリアルモニタを立ち上げたまま）Wio LTEをDFUモードに変更する

すると、Arduino IDEがVCOMを握ったままになってしまい、COM経由でスケッチを書き込もうとしてエラーになる。

**Comment by matsujirushi** [comment]
Arduino IDEを再起動すれば回復します。
